// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgh3vM3O7a6hR0_-YM0m89_Op4tvCStpQ',
    appId: '1:1002166006899:web:60cf0edf1c8b0726666606',
    messagingSenderId: '1002166006899',
    projectId: 'easybuy-1183a',
    authDomain: 'easybuy-1183a.firebaseapp.com',
    storageBucket: 'easybuy-1183a.firebasestorage.app',
    measurementId: 'G-Y5LB4DEJZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFy3KJ5HyzCXvrOM8aDzFwJhSEFz69GgQ',
    appId: '1:1002166006899:android:b1e44a40b915207a666606',
    messagingSenderId: '1002166006899',
    projectId: 'easybuy-1183a',
    storageBucket: 'easybuy-1183a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOIiZ9TB8BkGRdSqTrsyj52uT69Uzvr8',
    appId: '1:1002166006899:ios:783ed69b3287eadd666606',
    messagingSenderId: '1002166006899',
    projectId: 'easybuy-1183a',
    storageBucket: 'easybuy-1183a.firebasestorage.app',
    iosBundleId: 'com.noon.clone.noonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOIiZ9TB8BkGRdSqTrsyj52uT69Uzvr8',
    appId: '1:1002166006899:ios:783ed69b3287eadd666606',
    messagingSenderId: '1002166006899',
    projectId: 'easybuy-1183a',
    storageBucket: 'easybuy-1183a.firebasestorage.app',
    iosBundleId: 'com.noon.clone.noonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgh3vM3O7a6hR0_-YM0m89_Op4tvCStpQ',
    appId: '1:1002166006899:web:64c43291944f9198666606',
    messagingSenderId: '1002166006899',
    projectId: 'easybuy-1183a',
    authDomain: 'easybuy-1183a.firebaseapp.com',
    storageBucket: 'easybuy-1183a.firebasestorage.app',
    measurementId: 'G-CWP1G10WLL',
  );
}
